# Generated by Django 5.1.5 on 2025-02-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='parse_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
