# Generated by Django 5.1.5 on 2025-02-11 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='transaction_number',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Transaction number must be numeric', regex='^\\d+$')]),
        ),
    ]
