# Generated by Django 5.1.5 on 2025-02-11 16:44

import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0002_alter_receipt_transaction_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costcoitem',
            options={'ordering': ['item_code'], 'verbose_name': 'Costco Item', 'verbose_name_plural': 'Costco Items'},
        ),
        migrations.AlterModelOptions(
            name='costcowarehouse',
            options={'ordering': ['store_number'], 'verbose_name': 'Costco Warehouse', 'verbose_name_plural': 'Costco Warehouses'},
        ),
        migrations.AlterModelOptions(
            name='itempricehistory',
            options={'ordering': ['-date_changed'], 'verbose_name': 'Item Price History', 'verbose_name_plural': 'Item Price Histories'},
        ),
        migrations.AlterModelOptions(
            name='itemwarehouseprice',
            options={'verbose_name': 'Item Warehouse Price', 'verbose_name_plural': 'Item Warehouse Prices'},
        ),
        migrations.AlterModelOptions(
            name='lineitem',
            options={'ordering': ['id'], 'verbose_name': 'Line Item', 'verbose_name_plural': 'Line Items'},
        ),
        migrations.AlterModelOptions(
            name='priceadjustmentalert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Price Adjustment Alert', 'verbose_name_plural': 'Price Adjustment Alerts'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-transaction_date'], 'verbose_name': 'Receipt', 'verbose_name_plural': 'Receipts'},
        ),
        migrations.RemoveConstraint(
            model_name='receipt',
            name='unique_user_transaction',
        ),
        migrations.RemoveIndex(
            model_name='priceadjustmentalert',
            name='receipt_par_is_acti_8a772f_idx',
        ),
        migrations.AddField(
            model_name='costcowarehouse',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='costcowarehouse',
            name='state',
            field=models.CharField(default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='item_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(upload_to='receipts/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='store_city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='store_location',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='store_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transaction_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='costcoitem',
            index=models.Index(fields=['description'], name='receipt_par_descrip_803b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='costcoitem',
            index=models.Index(fields=['last_price_update'], name='receipt_par_last_pr_1675c8_idx'),
        ),
        migrations.AddIndex(
            model_name='costcowarehouse',
            index=models.Index(fields=['city', 'state'], name='receipt_par_city_042ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='lineitem',
            index=models.Index(fields=['item_code', 'price'], name='receipt_par_item_co_f5661f_idx'),
        ),
        migrations.AddIndex(
            model_name='lineitem',
            index=models.Index(fields=['receipt', 'item_code'], name='receipt_par_receipt_eabe28_idx'),
        ),
        migrations.AddIndex(
            model_name='lineitem',
            index=models.Index(fields=['created_at'], name='receipt_par_created_020d0c_idx'),
        ),
        migrations.AddIndex(
            model_name='priceadjustmentalert',
            index=models.Index(fields=['is_active', 'is_dismissed'], name='receipt_par_is_acti_c42acd_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', 'transaction_date'], name='receipt_par_user_id_910eab_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['store_location', 'store_number'], name='receipt_par_store_l_73a924_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['parsed_successfully'], name='receipt_par_parsed__d71d19_idx'),
        ),
    ]
