# Generated by Django 5.1.5 on 2025-02-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0002_clean_orphaned_lineitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='is_taxable',
            field=models.BooleanField(default=False),
        ),
    ]
