# Generated by Django 5.1 on 2025-05-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0004_add_on_sale_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceadjustmentalert',
            name='data_source',
            field=models.CharField(choices=[('ocr_parsed', 'OCR Parsed'), ('user_edit', 'User Edit')], default='ocr_parsed', help_text='Source of the price data that triggered this alert', max_length=20),
        ),
    ]
