# Generated by Django 5.1 on 2025-05-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0006_add_official_promotion_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialsaleitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='officialsaleitem',
            name='sale_type',
            field=models.CharField(choices=[('instant_rebate', 'Instant Rebate'), ('discount_only', 'Discount Only'), ('markdown', 'Markdown Sale'), ('member_only', 'Member Only Deal'), ('manufacturer', 'Manufacturer Coupon')], default='instant_rebate', max_length=20),
        ),
    ]
