# Generated by Django 5.1 on 2025-05-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0008_alter_receipt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/%d/'),
        ),
    ]
