# Generated by Django 5.1 on 2025-05-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0009_alter_receipt_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='original_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original total from receipt, separate from calculated price * quantity', max_digits=10, null=True),
        ),
    ]
