# Generated by Django 5.1 on 2025-06-17 15:51

from django.db import migrations, models


def remove_ocr_parsed_alerts(apps, schema_editor):
    """Remove all price adjustment alerts that were created from user-to-user comparisons."""
    PriceAdjustmentAlert = apps.get_model('receipt_parser', 'PriceAdjustmentAlert')
    
    # Delete all alerts with data_source='ocr_parsed' (user-to-user comparisons)
    deleted_count = PriceAdjustmentAlert.objects.filter(data_source='ocr_parsed').count()
    PriceAdjustmentAlert.objects.filter(data_source='ocr_parsed').delete()
    
    print(f"Removed {deleted_count} user-to-user price adjustment alerts")


def reverse_remove_ocr_parsed_alerts(apps, schema_editor):
    """Reverse migration - cannot restore deleted alerts."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0010_add_original_total_price'),
    ]

    operations = [
        migrations.RunPython(
            remove_ocr_parsed_alerts,
            reverse_remove_ocr_parsed_alerts,
        ),
        migrations.AlterField(
            model_name='priceadjustmentalert',
            name='data_source',
            field=models.CharField(choices=[('user_edit', 'User Edit'), ('official_promo', 'Official Promotion')], default='user_edit', help_text='Source of the price data that triggered this alert', max_length=20),
        ),
    ]
