# Generated by Django 5.1 on 2025-11-05 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0013_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Whether user has an active premium subscription'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free'), ('stripe', 'Stripe'), ('apple', 'Apple In-App Purchase')], default='free', help_text='Type of subscription: free, stripe, or apple', max_length=10),
        ),
        migrations.CreateModel(
            name='AppleSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Apple transaction ID', max_length=255)),
                ('original_transaction_id', models.CharField(db_index=True, help_text='Original transaction ID (unique identifier for the subscription)', max_length=255, unique=True)),
                ('product_id', models.CharField(db_index=True, help_text='Product identifier (e.g., com.priceadjustpro.monthly)', max_length=255)),
                ('receipt_data', models.TextField(help_text='Base64 encoded receipt data from Apple')),
                ('purchase_date', models.DateTimeField(help_text='Date of purchase')),
                ('expiration_date', models.DateTimeField(blank=True, help_text='Subscription expiration date', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether subscription is currently active')),
                ('is_sandbox', models.BooleanField(default=False, help_text='Whether this is a sandbox (test) purchase')),
                ('last_validation_response', models.JSONField(blank=True, help_text='Last response from Apple receipt validation', null=True)),
                ('last_validated_at', models.DateTimeField(blank=True, help_text='Last time this subscription was validated with Apple', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apple_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apple Subscription',
                'verbose_name_plural': 'Apple Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='receipt_par_user_id_871b31_idx'), models.Index(fields=['original_transaction_id'], name='receipt_par_origina_688d8c_idx'), models.Index(fields=['expiration_date'], name='receipt_par_expirat_421da9_idx')],
            },
        ),
    ]
