# Generated by Django 5.1 on 2025-11-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0016_verify_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='6-digit verification code', max_length=6, null=True),
        ),
    ]
