# Generated by Django 5.1 on 2026-01-24 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0019_make_store_fields_optional_for_price_adjustment_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email OTP',
                'verbose_name_plural': 'Email OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='pushdelivery',
            new_name='receipt_par_kind_8536cd_idx',
            old_name='receipt_pars_kind_e0aab0_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdelivery',
            new_name='receipt_par_device__69a337_idx',
            old_name='receipt_pars_device__4b8f02_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='receipt_par_user_id_581225_idx',
            old_name='receipt_pars_user_id_a1ed7a_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='receipt_par_user_id_fd152a_idx',
            old_name='receipt_pars_user_id_0e0b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='receipt_par_platfor_b1afef_idx',
            old_name='receipt_pars_platform_8a3cc9_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='receipt_par_last_se_f8fa81_idx',
            old_name='receipt_pars_last_se_8d7f3c_idx',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
    ]
