# Generated by Django 5.1 on 2026-02-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0020_emailotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionproduct',
            name='is_test_mode',
            field=models.BooleanField(default=False, help_text='Whether this is a test mode product/price'),
        ),
        migrations.AlterField(
            model_name='subscriptionproduct',
            name='stripe_product_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionproduct',
            unique_together={('stripe_price_id', 'is_test_mode')},
        ),
    ]
